version: '3.8'

services:
  backend_prod:
    image: registry.the-tip-top.site:5002/the-tip-top-back:latest-prod-back
    container_name: backend-prod
    restart: always
    depends_on:
      - postgres_prod
      - vault
    environment:
      APP_ENVIRONMENT: prod
      VAULT_ADDR: "http://51.77.244.16:8200"
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ~/environments/production/entrypoint.sh:/entrypoint.sh  # Monte le script au bon endroit
    entrypoint: ["/bin/sh", "-c", "
      chmod +x /entrypoint.sh &&
      exec /entrypoint.sh
    "]
    networks:
      - web
    labels:
      - traefik.enable=true
      - "traefik.http.routers.backend-prod.entrypoints=websecure"
      - "traefik.http.routers.backend-prod.rule=Host(`api.the-tip-top.site`)"
      - "traefik.http.services.backend-prod.loadbalancer.server.port=8087"  # Corrigé de 8087 à 8080
      - "traefik.http.routers.backend-prod.tls.certresolver=lets-encr"
      - "traefik.http.middlewares.forwardheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    ports:
      - "8087" # Expose le port interne de Tomcat pour le mapping

  frontend_prod:
    image: registry.the-tip-top.site:5000/the-tip-top-front:Front-prod-latest
    container_name: frontend-prod
    restart: always
    networks:
      - private
      - web
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-prod.rule=Host(`jeux-concours.the-tip-top.site`)"
      - "traefik.http.routers.frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.frontend-prod.tls.certresolver=lets-encr"

  postgres_prod:
    image: postgres:14
    container_name: postgres-prod
    restart: always
    ports:
    - "5435:5432"
    networks:
      - web
      - private
    environment:
      POSTGRES_USER: admin_prod
      POSTGRES_PASSWORD: prod_password
      POSTGRES_DB: prod_the_tip_top_db
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:

networks:
  web:
    external: true
  private:
    driver: bridge
